# Generated by Django 5.1.1 on 2024-09-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='id_teacher',
            new_name='teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(default='Descripción no disponible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='student', to='users.class'),
        ),
    ]
