# Generated by Django 5.1.1 on 2024-09-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_teacher_class_teacher_class_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_picture',
            field=models.ImageField(blank=True, default='class_photos/default_profile.png', null=True, upload_to='class_photos/'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
