# Generated by Django 5.1.1 on 2024-09-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorites',
        ),
        migrations.CreateModel(
            name='StudentFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.class')),
            ],
        ),
    ]
