# Generated by Django 5.1.1 on 2024-09-06 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_student_classes_remove_student_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfavorites',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentfavorites',
            name='student_class',
        ),
        migrations.CreateModel(
            name='StudentFavoritesClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFavoritesTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.DeleteModel(
            name='StudentFavorites',
        ),
    ]
