# Generated by Django 5.1.1 on 2024-09-18 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classCreation_Schedules', '0001_initial'),
        ('users', '0010_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfavoritesclasses',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classCreation_Schedules.class'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
