# Generated by Django 5.0.7 on 2024-09-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_studentfavoritesclasses_student_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='average_rating',
        ),
    ]
