# Generated by Django 5.1 on 2024-10-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_teacher_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfavoritesteachers',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentfavoritesteachers',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='StudentFavoritesClasses',
        ),
        migrations.DeleteModel(
            name='StudentFavoritesTeachers',
        ),
    ]
