# Generated by Django 5.1.2 on 2024-10-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_professorchatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfessorChatMessage',
        ),
    ]
