# Generated by Django 5.1.1 on 2024-10-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delete_professorchatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='specialties',
            new_name='specialities',
        ),
        migrations.AddField(
            model_name='teacher',
            name='ciudad',
            field=models.CharField(default='Colombia', max_length=150),
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
