# Generated by Django 5.1 on 2024-10-14 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classCreation_Schedules', '0001_initial'),
        ('users', '0013_remove_studentfavoritesteachers_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFavoritesClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classCreation_Schedules.class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFavoritesTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
