# Generated by Django 5.1 on 2024-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('class_picture', models.ImageField(blank=True, default='class_photos/default_profile.png', null=True, upload_to='class_photos/')),
                ('embedding', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
