# Generated by Django 5.1 on 2024-10-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number_correct_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='total_answers',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TF', 'Verdadero/Falso'), ('MC', 'Elección Múltiple')], max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
