# Generated by Django 5.1 on 2024-10-12 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classCreation_Schedules', '0001_initial'),
        ('users', '0012_remove_teacher_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classCreation_Schedules.class')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enrolled', 'Enrolled'), ('removed', 'Removed')], max_length=10)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classCreation_Schedules.class')),
            ],
        ),
    ]
